TEXT_GAMEOVER  = "I'M SORRY, NO MORE CREDITS TO PLAY";
TEXT_PLAY      = "PLAY";
TEXT_CREDITS   = "CREDITS";
TEXT_SPIN      = "SPIN";
TEXT_PLUS      = "+";
TEXT_MIN       = "-";
TEXT_CURRENCY  = "$";
TEXT_HELP1     = 'CLICK ON "+" or "-" BUTTONS TO SELECT YOUR BET. PRIZE WILL VARY ACCORDING TO THE WAGER. THE MORE YOU BET, THE MORE YOU CAN WIN. WHEN YOU ARE READY, SPIN THE WHEEL TO PLAY!';
TEXT_HELP2     = "WHEN THE WHEEL STOPS SPINNING, YOU'LL BE SHOWN YOUR PRIZE!";
TEXT_ALERT     = "wheel_settings PROBABILITY CHECK FAILED: win_occurence number sum must be 100! Please read paragraph in the documentation for more help.";
var TEXT_CREDITS_DEVELOPED = "DEVELOPED BY";
var TEXT_PRELOADER_CONTINUE = "START";

TEXT_SHARE_IMAGE = "200x200.jpg";
TEXT_SHARE_TITLE = "Congratulations!";
TEXT_SHARE_MSG1 = "You collected <strong>";
TEXT_SHARE_MSG2 = " points</strong>!<br><br>Share your score with your friends!";
TEXT_SHARE_SHARE1 = "My score is ";
TEXT_SHARE_SHARE2 = " points! Can you do better?";