TEXT_MONEY     = "MONEY";
TEXT_CUR_BET   = "CUR BET";
TEXT_PLAY      = "PLAY";
TEXT_BET       = "BET";
TEXT_COIN      = "COIN";
TEXT_MIN_BET   = "MIN BET";
TEXT_MAX_BET   = "MAX BET";
TEXT_SPIN      = "SPIN";
TEXT_EXIT      = "EXIT";
TEXT_RECHARGE  = "RECHARGE";
TEXT_NEIGHBORS = "NEIGHBORS";
TEXT_FINALSBET = "FINALS BET";
TEXT_REBET     = "REBET";
TEXT_WIN       = "WIN";
TEXT_HISTORY   = "HISTORY";
TEXT_YOU_WIN   = "YOU WON";
TEXT_YOU_LOSE  = "YOU LOST"; 
TEXT_CURRENCY  = "$";

TEXT_ERROR_NO_MONEY_MSG="NOT ENOUGH MONEY FOR THIS BET!!";
TEXT_ERROR_MAX_BET_REACHED="MAX BET REACHED!!";
TEXT_ERROR_MIN_BET = "YOU BET IS LOWER THAN MINIMUM BET!!";
TEXT_NO_MONEY = "YOU DON'T HAVE ENOUGH MONEY!!!";
TEXT_RECHARGE_MSG = "PLEASE CLICK RECHARGE BUTTON TO PLAY AGAIN";

var TEXT_CREDITS_DEVELOPED = "DEVELOPED BY";
var TEXT_LINK = "WWW.CODETHISLAB.COM";

TEXT_CONGRATULATIONS = "Congratulations!";
TEXT_SHARE_1 = "You collected <strong>";
TEXT_SHARE_2 = " points</strong>!<br><br>Share your score with your friends!";
TEXT_SHARE_3 = "My score is ";
TEXT_SHARE_4 = " points! Can you do better?";				